const express = require("express")
const {homeRoute} = require("./routes/home")
const { signupRoute } = require("./routes/signup")
const { signinRoute } = require("./routes/signin")
const { signoutRoute } = require("./routes/signout")
const {createpostRoute} = require("./routes/createpost")
const {editPostRoute} = require("./routes/editpost")
const { viewPostRoute } = require("./routes/viewpost")
const {sessionAuthorization, redirectIfLoggedIn} = require("./middlewares/sessionAuthorization")
const { connectdb } = require("./models")
const { userModel, postModel } = require("./models/models")
const bodyParser = require("body-parser")
const session = require("express-session")
const { commentRoute } = require("./routes/createComment")
const { deletePostRouter } = require("./routes/deletePost")
const { deleteCommentRouter } = require("./routes/deleteComment")
// require("dotenv")

connectdb()
const app = express()
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended: true}))
app.set("view engine", "ejs")
app.use(express.static("public"))
app.use(session({secret: "dev"}))
app.use(homeRoute)
app.use("/auth", signoutRoute)
app.use("/auth",redirectIfLoggedIn, signupRoute)
app.use("/auth", redirectIfLoggedIn, signinRoute)
app.use(sessionAuthorization,createpostRoute)
app.use(sessionAuthorization, editPostRoute)
app.use(sessionAuthorization, deletePostRouter)
app.use(sessionAuthorization, deleteCommentRouter)
app.use(viewPostRoute)
app.use(commentRoute)




app.listen(3000)
